### ISSUE TITLE
Push 0.1.2 version to GitHub, please

### ISSUE THREAD

**Issue by svetlyak40wt** [perenecabuto/django-sendmail-backend#6]
Latest version on PyPi is 0.1.2, but at the GitHub — 0.1.1. Felipe, please, push your changes to the GitHub.

**Comment by svetlyak40wt** [comment]
Are there any news here?

**Comment by mrts** [comment]
You can install it with `pip` as follows meanwhile:

```
pip install git+http://github.com/perenecabuto/django-sendmail-backend.git
```

**Comment by svetlyak40wt** [comment]
I know. By the way, it is better to pin a git hash in the requirements.

**Comment by mrts** [comment]
Thanks, good point, so here goes:

```
pip install git+http://github.com/perenecabuto/django-sendmail-backend.git@00505e9b000e9d3eb669d8e50f8baa186c95cc2e
```

**Comment by svetlyak40wt** [comment]
Closing this old issue. Thanks to https://12forks.com MVP for pointing to it.
